FROM ubuntu:22.04

ENV SHELL /bin/bash

WORKDIR /app

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  curl && \
  curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
  apt-get install -y --fix-missing nodejs && \
  npm install firebase && \
  npm install -g firebase-tools@11.29.1

RUN apt-get install -y --fix-missing curl openjdk-18-jdk