FROM node:16.12.0-alpine3.14

ENV SHELL /bin/bash

WORKDIR /app

# openjdk11より上のバージョンをインストールする場合に下記のリポジトリをローカルに作成する必要がある
# RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update && \
  apk add --no-cache openjdk11-jdk && \
  npm install firebase && \
  npm install -g firebase-tools@11.28